---
# tasks file for lbserver
- name: install haproxy package
  package:
      name: "haproxy"
      state: present

- name: conf lb server
  template:
     dest: /etc/haproxy/haproxy.cfg
     src: templates/haproxy.cfg.j2
  notify: service haproxy restart

- name: start service for lb
  service:
      name: "haproxy"
      state: started
  
      
